server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/student_info?user=root
    username: root
    password: 123456
  mvc:
    cors:
      allowed-origins: "*"
      allowed-methods: "*"
      allowed-headers: "*"
      allow-credentials: true
      max-age: 18000

mybatis:
  mapper-locations: classpath:mapper/*.xml
  # type-aliases-package: com.example.demo.model

